const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const fs=require('fs'),path=require('path');
(async()=>{
 const browser=await chromium.launch({headless:true,executablePath:process.env.CHROMIUM_PATH});
 const page=await browser.newPage({viewport:{width:1500,height:1000}}),errors=[];
 page.on('pageerror',e=>errors.push(String(e)));
 const out=path.resolve(__dirname,'../validation/integration-review');
 await page.goto('http://127.0.0.1:8766',{waitUntil:'domcontentloaded'});
 await page.getByText('300 matching cells',{exact:true}).waitFor();
 await page.getByRole('button',{name:'Integration · segmentation & CN',exact:true}).click();
 await page.getByRole('button',{name:'Generate alternative flank view',exact:true}).waitFor({timeout:120000});
 const meta=await (await page.request.get('http://127.0.0.1:8766/api/integration/meta')).json();
 if(meta.flank_scores?.length!==162||meta.screening?.length!==196||meta.bootstrap?.length!==196||meta.review_summary?.length!==35||meta.manifest?.totals_default?.merged_boundaries!==0)throw new Error('Verified original diagnostic tables not loaded');
 const candidates=await (await page.request.get('http://127.0.0.1:8766/api/integration/candidates?source=cluster4&chrom=chr8')).json();
 if(!candidates.rows.length)throw new Error('Original candidate audit not loaded');
 await page.getByRole('button',{name:'Generate alternative flank view',exact:true}).click();
 await page.getByLabel('Alternative segment',{exact:true}).waitFor();
 const count=await page.getByLabel('Alternative segment',{exact:true}).locator('option').count();
 if(count<1)throw new Error('Expected internal chr8 segments');
 await page.getByLabel('Alternative level estimate',{exact:true}).selectOption('iqr_mean');
 let download=page.waitForEvent('download');
 await page.getByRole('button',{name:'Download alternative JSON',exact:true}).click();
 await(await download).saveAs(path.join(out,'generated-flanks.json'));
 download=page.waitForEvent('download');await page.getByRole('button',{name:'Download alternative CSV',exact:true}).click();
 await(await download).saveAs(path.join(out,'generated-flanks.csv'));
 await page.getByRole('button',{name:'Compute paired cell bootstrap',exact:true}).click();
 await page.getByRole('button',{name:'Download bootstrap JSON',exact:true}).waitFor({timeout:90000});
 download=page.waitForEvent('download');await page.getByRole('button',{name:'Download bootstrap JSON',exact:true}).click();
 await(await download).saveAs(path.join(out,'generated-bootstrap.json'));
 await page.locator('.alternative-flanks').screenshot({path:path.join(out,'alternative-flanks.png')});
 await page.getByLabel('Alternative maximum bins',{exact:true}).fill('99');
 await page.getByText(/Settings changed; showing the previous generated result/).waitFor();
 await page.getByRole('checkbox',{name:'allelic |dBAF| pseudobulk (right axis)',exact:true}).check();
 await page.getByLabel(/^track level/).selectOption('raw');
 await page.locator('#cluster-tracks').scrollIntoViewIfNeeded();
 const plot=page.locator('#cluster-tracks .js-plotly-plot').first();
 await plot.scrollIntoViewIfNeeded();
 const axes=await plot.evaluate(el=>({range:el._fullLayout.yaxis.range,allelic:el.data.filter(t=>String(t.name).includes('allelic')).map(t=>({name:t.name,axis:t.yaxis,valid:!!el._fullLayout['yaxis'+t.yaxis.slice(1)],text:t.text?.find(Boolean)}))}));
 if(axes.range[1]>1e6||axes.allelic.length!==5||axes.allelic.some(a=>!a.valid||!a.text.includes('nonzero imbalance')))throw new Error('Incorrect track axes or coverage label: '+JSON.stringify(axes));
 await plot.screenshot({path:path.join(out,'raw-depth-allelic-tracks.png')});
 const diagnostics=page.locator('.panel').filter({has:page.getByRole('heading',{name:/Small-segment diagnostics across/})});
 await diagnostics.scrollIntoViewIfNeeded();
 const diagnosticSlots=diagnostics.locator('.deferred-plot');
 for(let i=0;i<await diagnosticSlots.count();i++){await diagnosticSlots.nth(i).scrollIntoViewIfNeeded();await diagnosticSlots.nth(i).locator('.js-plotly-plot').waitFor();}
 await diagnostics.screenshot({path:path.join(out,'original-diagnostics.png')});
 await diagnostics.locator('.js-plotly-plot').first().evaluate(el=>{
  const trace=el.data.find(t=>t.customdata?.length);
  if(!trace)throw new Error('Missing diagnostic points');
  el.emit('plotly_click',{points:[{customdata:trace.customdata[0]}]});
 });
 await page.getByText(/Original median bootstrap fraction/).waitFor();
 await page.getByText(/Merge prototype summary \(τ/).click();
 await page.getByText(/Original prototype: median segment levels/).waitFor();
 await page.getByRole('button',{name:'Integration · clusters',exact:true}).click();
 await page.locator('.emb-grid .js-plotly-plot').first().waitFor();
 await page.screenshot({path:path.join(out,'clusters.png')});
 if(errors.length)throw new Error(errors.join('\n'));
 fs.writeFileSync(path.join(out,'browser-results.json'),JSON.stringify({segments:count,original_flank_rows:meta.flank_scores.length,original_screening_rows:meta.screening.length,original_bootstrap_rows:meta.bootstrap.length,candidate_audit_rows:candidates.rows.length,original_diagnostic_selection:true,merge_summary:true,paired_bootstrap:true,exports:true,stale_state:true,axes,errors},null,2));
 console.log('PASS integration generation, bootstrap, exports, stale state, raw/allelic axes, cluster tab');
 await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
